SENHA_ADM = "admin123"
SUPABASE_URL="https://geiilpopiehhnfvumugb.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlaWlscG9waWVoaG5mdnVtdWdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwMDE4ODIsImV4cCI6MjA4NjU3Nzg4Mn0.unigIe9DuG-4lS_ynfxpMV9FsE2v-O5jwg6hu7VIW-M"
DISCORD_WEBHOOK_URL="https://discord.com/api/webhooks/1471963394977304699/d0f6ken9RiTKnvosB4i4ojFJH5nquw-8Xhb-kKW2_IVTlqcmIJFg7fCx914bx6Kj4m9y"

